version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=94df62cv32ch64dg97dgef
      - DATABASE_URL=mysql://root:example@db/Turing
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=Turing
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
